1. Сгенерировать датасет при помощи sklearn.datasets.make_regression и обучить линейную модель при помощи градиентного спуска (GD) и (стохастического градиентного спуска (SGD) или mini-batch градиентного спуска). Построить графики среднеквадратичной ошибки от числа итераций для обоих методов на одном рисунке, сделать выводы о разнице скорости сходимости каждого из методов.

In [3]:
from sklearn import datasets

X, y, coef = datasets.make_regression(n_samples = 100,
                                     n_features = 2,
                                     n_informative = 2,
                                     n_targets = 1,
                                     noise = 5,
                                     coef = True,
                                     random_state = 42)

In [4]:
import numpy as np
from sklearn import datasets
import matplotlib.pyplot as plt

%matplotlib inline

In [11]:
def calc_mse(y, y_pred):
    err = np.mean((y - y_pred)**2)
    return err

In [43]:
def eval_GD(X, y, iterations, alpha=1e-4):
    np.random.seed(42)
    w = np.random.randn(X.shape[1])
    n = X.shape[0]
    iter_num = 0
    errors = []
    for i in range(1, iterations + 1):
        y_pred = np.dot(X, w)
        err = calc_mse(y, y_pred)
        w -= alpha * (1/n * 2 * np.dot((y_pred - y), X))
        iter_num += 1
        errors.append(mserror(X, w, y))
        if i % (iterations / 10) == 0:
            print(i, w, err)
    return w

In [18]:
w_gd = eval_GD(X, y, iterations=1500, alpha=1e-2)
y_pred = np.dot(X, w_gd)
err_gb = calc_mse(y, y_pred)
print(err_gb)

150 [77.98812456 70.84245251] 101.00012031045404
300 [85.91949688 73.98513742] 29.447749543149758
450 [86.75340147 74.10013615] 28.772456569533798
600 [86.84223393 74.10142749] 28.764997644042495
750 [86.85175568 74.10101565] 28.764911965729777
900 [86.85277925 74.10094392] 28.764910973046263
1050 [86.85288943 74.10093483] 28.764910961523615
1200 [86.85290129 74.10093378] 28.764910961389795
1350 [86.85290257 74.10093367] 28.764910961388267
1500 [86.85290271 74.10093366] 28.76491096138825
28.76491096138823


In [21]:
def eval_SGD (X, y, iterations, qty_in_batch=1, alpha=1e-4):
    np.random.seed(42)
    w = np.random.randn(X.shape[1])
    n = X.shape[0]
    n_batch = n // qty_in_batch
    if n % qty_in_batch != 0:
        n_batch += 1
    for i in range(1, iterations + 1):
        for b in range(n_batch):
            start_ = qty_in_batch * b
            end_ = qty_in_batch * (b+1)
            X_tmp = X[start_ : end_, :]
            y_tmp = y[start_ : end_]
            y_pred_tmp = np.dot(X_tmp, w)
            err = calc_mse(y_tmp, y_pred_tmp)
            w = alpha * (1/n * 2 * np.dot((y_pred_tmp - y_tmp), X_tmp))
        if i % (iterations / 10) == 0:
            print(i, w, err)
    return w

In [38]:
w_sgd = eval_SGD(X, y, iterations=1500, qty_in_batch=1, alpha=1e-2)
y_spred = np.dot(X, w_sgd)
err_sgb = calc_mse(y, y_spred)
print(err_sgb)

150 [-0.0039406  -0.01185478] 5747.91189398044
300 [-0.0039406  -0.01185478] 5747.91189398044
450 [-0.0039406  -0.01185478] 5747.91189398044
600 [-0.0039406  -0.01185478] 5747.91189398044
750 [-0.0039406  -0.01185478] 5747.91189398044
900 [-0.0039406  -0.01185478] 5747.91189398044
1050 [-0.0039406  -0.01185478] 5747.91189398044
1200 [-0.0039406  -0.01185478] 5747.91189398044
1350 [-0.0039406  -0.01185478] 5747.91189398044
1500 [-0.0039406  -0.01185478] 5747.91189398044
11339.565864913526


In [39]:
eval_SGD (X, y, iterations=1500, qty_in_batch=1, alpha=1e-4)

150 [-3.94028676e-05 -1.18538294e-04] 5746.992255019007
300 [-3.94028676e-05 -1.18538294e-04] 5746.992255019007
450 [-3.94028676e-05 -1.18538294e-04] 5746.992255019007
600 [-3.94028676e-05 -1.18538294e-04] 5746.992255019007
750 [-3.94028676e-05 -1.18538294e-04] 5746.992255019007
900 [-3.94028676e-05 -1.18538294e-04] 5746.992255019007
1050 [-3.94028676e-05 -1.18538294e-04] 5746.992255019007
1200 [-3.94028676e-05 -1.18538294e-04] 5746.992255019007
1350 [-3.94028676e-05 -1.18538294e-04] 5746.992255019007
1500 [-3.94028676e-05 -1.18538294e-04] 5746.992255019007


array([-3.94028676e-05, -1.18538294e-04])

In [31]:
from sklearn import preprocessing

X_norm = X.copy().astype(np.float64)
X_norm = preprocessing.normalize(X_norm)

In [40]:
eval_SGD (X_norm, y, iterations=1500, qty_in_batch=1, alpha=1e-4)

150 [-4.78257057e-05 -1.43877284e-04] 5746.9927434369665
300 [-4.78257057e-05 -1.43877284e-04] 5746.9927434369665
450 [-4.78257057e-05 -1.43877284e-04] 5746.9927434369665
600 [-4.78257057e-05 -1.43877284e-04] 5746.9927434369665
750 [-4.78257057e-05 -1.43877284e-04] 5746.9927434369665
900 [-4.78257057e-05 -1.43877284e-04] 5746.9927434369665
1050 [-4.78257057e-05 -1.43877284e-04] 5746.9927434369665
1200 [-4.78257057e-05 -1.43877284e-04] 5746.9927434369665
1350 [-4.78257057e-05 -1.43877284e-04] 5746.9927434369665
1500 [-4.78257057e-05 -1.43877284e-04] 5746.9927434369665


array([-4.78257057e-05, -1.43877284e-04])

2.Модифицировать решение первого задания путем добавления L2 регуляризации и сравнить результаты.

In [44]:
def eval_GD_reg(X, y, iterations, alpha=1e-4, lambda_=1e-8):
    np.random.seed(42)
    w = np.random.randn(X.shape[1])
    n = X.shape[0]
    for i in range(1, iterations + 1):
        y_pred = np.dot(X, w)
        err = calc_mse(y, y_pred)
        w -= alpha * (1/n * 2 * np.dot((y_pred - y), X)+ 2 * lambda_ * w)
        if i % (iterations / 10) == 0:
            print(i, w, err)
    return w

In [48]:
eval_GD_reg(X, y, iterations=1000, alpha=1e-4, lambda_=0)

100 [1.79846799 1.35553997] 10904.050657995775
200 [3.08042621 2.81948751] 10525.281539741083
300 [4.34289314 4.25417218] 10159.958156376426
400 [5.58616835 5.66017611] 9807.594973927788
500 [6.81054675 7.03806986] 9467.724253232162
600 [8.01631868 8.38841269] 9139.895389567284
700 [9.20376994 9.71175277] 8823.674277040302
800 [10.37318187 11.0086274 ] 8518.642696799427
900 [11.52483146 12.27956325] 8224.397728168227
1000 [12.65899137 13.52507651] 7940.5511818364685


array([12.65899137, 13.52507651])